# -*- coding: utf-8 -*-
"""e_approximation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GikHSFYd5fy_6DiqxIgYwSQ0cJUaZx7
"""

print(list(range(2,4)))
from math import e
print(e)

import math



def approx_function(value, tol):
  best_estimate = round(value)
  error = abs(best_estimate - value)
  denominator = 1
  i = 2
  while True:
    high_estimate = math.ceil(i*value)/i
    low_estimate = math.floor(i*value)/i
    estimates = [low_estimate, high_estimate]
    error_list = [abs(low_estimate - value), abs(high_estimate - value)]
    min_error = min(error_list)
    if min_error < tol:
      best_estimate = estimates[error_list.index(min_error)]
      error = min_error
      denominator = i
      break
    i += 1
  s = str(int(best_estimate * denominator))+"/"+str(denominator)
  return (s, error)

print(approx_function(math.e, 1e-15))

sum = 0
for i in range(30):
  sum += (1/math.factorial(i))
print(sum)
print(28245729/10391023)
print(math.e)