# -*- coding: utf-8 -*-
"""factorial_polynomial_approximation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3Yt_rh-BPIZEijWFCM0pwKX5U0-7iBB
"""

import numpy as np
import matplotlib.pyplot as plt

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import math

np.random.seed(0)
X = np.arange(10, 100)
y = []
for i in X:
  y.append(math.log10(math.factorial(i)))
y = np.array(y)

def create_logreg_model(degree):
  X_local = np.power(X, degree).reshape(-1, 1)
  reg = LinearRegression().fit(X_local, y)
  score = reg.score(X_local, y)
  return [degree, score, reg.coef_[0], reg.intercept_]



degree_list = []
score_list = []
coef_list = []
intercept_list = []
for i in np.linspace(0, 30, num=601).tolist():
  j = create_logreg_model(i)
  degree_list.append(i)
  score_list.append(j[1])
  coef_list.append(j[2])
  intercept_list.append(j[3])

opt = score_list.index(max(score_list))
opt_degree = degree_list[opt]
opt_coef = coef_list[opt]
opt_intercept = intercept_list[opt]
print("Optimal Degree: ", opt_degree)
print("Optimal Coefficient: ", opt_coef)
print("Optimal Intercept: ", opt_intercept)
print("Score of Optimal Function: ", max(score_list))

def fit_polynomial(deg, coef, inter, c):
  return coef * (c**deg) + inter

mse = 0
for i in list(X):
  print(i, math.log10(math.factorial(i)), fit_polynomial(opt_degree, opt_coef, opt_intercept, i))
  mse += (math.log10(math.factorial(i)) - fit_polynomial(opt_degree, opt_coef, opt_intercept, i))**2

mse /= len(list(X))

print("MSE", mse)

# Fit a polynomial to the factorial values
degree = 10  # Adjust the degree as needed for better approximation
coefficients = np.polyfit(degree_list, score_list, degree)
poly = np.poly1d(coefficients)

# Plot the original factorial function and the polynomial approximation
plt.figure(figsize=(8, 6))
plt.plot(degree_list, score_list, label='Factorial Function')
plt.plot(degree_list, poly(degree_list), label='Polynomial Approximation', linestyle='--')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Factorial Function vs. Polynomial Approximation')
plt.legend()
plt.grid(True)
plt.show()

# Display the polynomial coefficients
print("Polynomial Coefficients:")
print(poly)