# -*- coding: utf-8 -*-
"""taylor_series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PZLcqTcXAvFfFhRqn4Hb2Wqvg9mMfwa
"""

import math
import numpy as np
def ex(c):
  l = []
  for i in c:
    l.append(math.e**i)
  return l

def taylor_e(x):
  l = []
  for i in x:
    sum = 0
    for j in range(6):
      sum += ((i**j)/(math.factorial(j)))
    l.append(sum)
  return l


# importing the required modules
import matplotlib.pyplot as plt
import numpy as np

# setting the x - coordinates
x = np.arange(0, 2, 0.1).tolist()
# setting the corresponding y - coordinates
y1 = ex(x)
y2 = taylor_e(x)

# plotting the points
plt.plot(x, y1)
plt.plot(x, y2)

# function to show the plot
plt.show()

def sin(c):
  l = []
  for i in c:
    l.append(math.sin(i))
  return l

def taylor_sin(x):
  l = []
  for i in x:
    sum = 0
    for j in range(30):
      sum += math.pow(-1, j)*((i**(j*2 + 1))/(math.factorial(2*j + 1)))
    l.append(sum)
  return l


# importing the required modules
import matplotlib.pyplot as plt
import numpy as np

# setting the x - coordinates
x = np.arange(0, 20, 0.1).tolist()
# setting the corresponding y - coordinates
y1 = sin(x)
y2 = taylor_sin(x)

# plotting the points
plt.plot(x, y1)
plt.plot(x, y2)

# function to show the plot
plt.show()

def cos(c):
  l = []
  for i in c:
    l.append(math.cos(i))
  return l

def taylor_cos(x):
  l = []
  for i in x:
    sum = 0
    for j in range(30):
      sum += math.pow(-1, j)*((i**(j*2))/(math.factorial(2*j)))
    l.append(sum)
  return l


# importing the required modules
import matplotlib.pyplot as plt
import numpy as np

# setting the x - coordinates
x = np.arange(0, 20, 0.1).tolist()
# setting the corresponding y - coordinates
y1 = cos(x)
y2 = taylor_cos(x)

# plotting the points
plt.plot(x, y1)
plt.plot(x, y2)

# function to show the plot
plt.show()